import React from "react";
import {
  FaRegFileAlt,
  FaStream,
  FaStar,
  FaGopuram,
  FaPodcast,
  FaFileSignature,
  FaBell,
  FaShoppingBag,
  FaWallet,
  FaHome,
  FaUserEdit,
  FaAdversal,
  FaStore,
  FaUsers,
  FaCircle,
  FaCog,
  FaQuestionCircle,
  FaSlidersH,
  FaUser,
  FaShoppingCart,
  FaGift,
  FaProductHunt,
  FaList,
  FaCode,
  FaCodeBranch,
  FaCircleNotch,
} from "react-icons/fa";
import * as Icon from "react-feather";
import { BsImage } from "react-icons/bs";
import { MdOutlineFolderSpecial } from "react-icons/md";
import { GiWantedReward } from "react-icons/gi";
import { CiDiscount1 } from "react-icons/ci";
import { TbTruckDelivery } from "react-icons/tb";
import { AiFillBell } from "react-icons/ai";
import { FiBarChart2 } from "react-icons/fi";

// eslint-disable-next-line no-sparse-arrays
const navigationConfig = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "item",
    icon: <FaHome size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/dashboard",
  },
  {
    type: "groupHeader",
    groupTitle: "Accounts",
    title: "Customers",
  },
  {
    id: "Customer",
    title: "Customers",
    type: "collapse",
    icon: <FaUsers size={15} />,
    children: [
      {
        id: "reate staff",
        title: "Create staff",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/account/CreateAccount",
      },
      {
        id: "Customer Registration",
        title: "Customer Registration",
        type: "item",
        icon: <FaUserEdit size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/Customer/Customer_Registration",
      },
      {
        id: "Staff List",
        title: "Staff List",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/userlist",
      },
      // {
      //   id: "clientAccounts",
      //   title: "Client Account",
      //   type: "item",
      //   icon: <FaCircle size={15} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/SoftNumen/userlist",
      // },
      // {
      //   id: "accountantaccounts",
      //   title: "Accountant Account",
      //   type: "item",
      //   icon: <FaCircle size={15} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/house/AddProduct",
      // },
      {
        id: "Assign Role",
        title: "Assign Role",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/account/addRoleNew",
      },
      {
        id: "Role List",
        title: "Role List",
        type: "item",
        icon: <FaUsers size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/Trupee/account/RoleList",
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "System Managment",
    title: "System Managment",
  },
  {
    id: "systemManagment",
    title: "System Managment",
    type: "collapse",
    icon: <FaProductHunt size={15} />,
    children: [
      // {
      //   id: "Product Registration",
      //   title: "Product Registration",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/SoftNumen/house/ProductRegistration",
      // },
      {
        id: "Scheduler",
        title: "Import",
        type: "item",
        icon: <MdOutlineFolderSpecial size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/parts/SchedulerTime",
      },
      {
        id: "Spare Part",
        title: "Spare Part",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/SparePartsSystem",
      },

      {
        id: "orders",
        title: "Orders",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/OrdersSystem",
      },

      {
        id: "Parts Catelog",
        title: "Parts Catelogue",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/parts/PartCatalougue",
      },
      {
        id: "Scrutiny/inspections",
        title: "Scrutiny/inspections",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/ScrutinySystem",
      },
      {
        id: "Invoice/Billing",
        title: "Invoice/Billing",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/InVoiceSystem",
      },
      {
        id: "supports",
        title: "Supports",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/SupportsSystem",
      },
      {
        id: "service",
        title: "Service",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/ServiceSystem",
      },
      // {
      //   id: "service",
      //   title: "Service",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/Trupee/account/RoleList",
      // },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "WAREHOUSE MANAGEMENT",
    title: "WAREHOUSE",
  },
  {
    id: "WAREHOUSE",
    title: "WAREHOUSE",
    type: "collapse",
    icon: <FaProductHunt size={15} />,
    children: [
      {
        id: "Create Warehouse",
        title: "Create Warehouse",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/WareHouseListSoft",
      },
    ],
  },

  {
    type: "groupHeader",
    groupTitle: "Quotation MANAGEMENT",
    title: "Quotation",
  },
  {
    id: "Quotation",
    title: "Quotation",
    type: "collapse",
    icon: <FaProductHunt size={15} />,
    children: [
      {
        id: "Add Supplier",
        title: "Add Supplier",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/SupplierList",
      },
      {
        id: "Create Quote",
        title: "Create Quote",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/CreateQuote",
      },
      {
        id: "Edit Notes",
        title: "Edit Notes",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/EditNotes",
      },
      {
        id: "Debit Notes",
        title: " Debit Notes",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/DebitNotes",
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "Product Managment",
    title: "Product Managment",
  },
  {
    id: "Product Managment",
    title: "Product Managment",
    type: "collapse",
    icon: <FaProductHunt size={15} />,
    children: [
      {
        id: "Product Registration",
        title: "Product Registration",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/product/ProductRegistration",
      },
      {
        id: "Product Search",
        title: "Product Search",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/product/ProductSearch",
      },
      {
        id: "createCampaign",
        title: "Create Campaign",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/createCampaign",
      },
      {
        id: "CampaignList",
        title: "Campaign List",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/Campaignlist",
      },
      // {
      //   id: "assigntoclient",
      //   title: "Assign To Client",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/house/assigntoclient",
      // },
      // {
      //   id: "assignedtoclient",
      //   title: "Assigned List",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/house/Assignedtoclient",
      // },
      // {
      //   id: "ratemaster",
      //   title: "Rate Master",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/house/ratemaster",
      // },
      // {
      //   id: "inventory",
      //   title: "Inventory",
      //   type: "item",
      //   icon: <FaProductHunt size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/house/inventory",
      // },
      // {
      //   id: "servicemaster",
      //   title: "Service Master",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/house/serviceMaster",
      // },
      {
        id: "Attribute",
        title: "Attribute",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/product/ProductAttribute",
      },
      // {
      //   id: "productlist",
      //   title: "ProductList",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/house/houseProductList",
      // },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "Parts Management",
    title: "Parts",
  },
  // {
  //   id: "Scheduler",
  //   title: "Scheduler Time",
  //   type: "collapse",
  //   icon: <FaList size={15} />,
  // },

  {
    id: "Parts",
    title: "Parts",
    type: "collapse",
    icon: <FaList size={15} />,
    children: [
      {
        id: "Parts List",
        title: "Parts List",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        // navLink: "/app/SoftNumen/parts/AddPart",
        navLink: "/app/SoftNumen/parts/PartList",
      },
      {
        id: "Parts Catalogue",
        title: "Parts Catalogue",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/parts/PartCatalougue",
      },
      {
        id: "Product Type",
        title: "Product Type",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/inhouse/productType",
        // navLink: "/app/freshlist/category/categoryList",
      },
      {
        id: "Model Type",
        title: "Model Type",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/Producttype/ModalTypeList",
      },
      {
        id: "Variant",
        title: "Variant",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/Producttype/VariantList",
      },
      {
        id: "Engine Type",
        title: "Engine Type",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/Producttype/EngineType",
      },
      {
        id: "Valves",
        title: "Valves",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/Producttype/ValvesTypeList",
      },
      {
        id: "Body Style",
        title: "Body Style",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/Producttype/BodyStyleList",
      },
      {
        id: "Colors",
        title: "Colors",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/Producttype/ColorList",
      },
      {
        id: "Product Name",
        title: "Product Name",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/Producttype/ProductNamelist",
      },
    ],
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Brand Management",
  //   title: "Brand",
  // },
  // {
  //   id: "brand",
  //   title: "Brand",
  //   type: "collapse",
  //   icon: <FaList size={15} />,
  //   children: [
  //     {
  //       id: "brandlist",
  //       title: "Brand List",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/brand/BrandList",
  //     },
  //     {
  //       id: "Category List",
  //       title: "Category List",
  //       type: "item",
  //       icon: <FaList size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/category/categoryList",
  //     },
  //   ],
  // },
  {
    type: "groupHeader",
    groupTitle: "Order Management",
    title: "Order Management",
  },
  {
    id: "order",
    title: "Order Management",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "all",
        title: "Place Order",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/order/placeorder",
      },
      {
        id: "pending ",
        title: "Order Pending",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/order/pending",
      },
      {
        id: "confirmed",
        title: "Order Received List",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/order/received",
      },
      // {
      //   id: "inprocess ",
      //   title: "In Process (17)",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/order/inprocess",
      // },
      // {
      //   id: "outfordelivery",
      //   title: "Out for delivery (09)",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/order/outfordelivery",
      // },
      {
        id: "delivery",
        title: "Completed Order List",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/order/completed",
      },
      {
        id: "Rejected",
        title: "Rejected",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softnumen/rejectedRequest",
      },
      // {
      //   id: "failedtodeliver",
      //   title: "Failed to Deliver",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/order/failedtodeliver",
      // },
      {
        id: "return",
        title: "Return",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/order/returned",
        // navLink: "/app/softNumen/order/canceled",
      },
      {
        id: "canceled",
        title: "Canceled",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/order/canceled",
      },
      {
        id: "PaymentGateway",
        title: "Payment Gateway",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/order/PaymentGateway",
      },
      {
        id: "ordertracking",
        title: "Order Tracking",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/order/OrderTracking",
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "BILLINGS",
    title: "BILLINGS",
  },
  {
    id: "BILLINGS",
    title: "BILLINGS",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "Purchaseinvoices",
        title: "Purchase invoices",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softnumen/order/purchaseinvoices",
      },
      // {
      //   id: "Bills",
      //   title: "Bills",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/subcategory/Bills",
      // },
      {
        id: "Merge invoices",
        title: "Merge invoices",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softnumen/InvoiceGenerator",
      },
      {
        id: "addtax",
        title: "Add tax",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softnumen/AddTaxSoft",
      },
      {
        id: "Courier/Shipping Charges",
        title: "Courier/Shipping Charges",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softnumen/CourierShipping",
      },
      // {
      //   id: "invoice Re-Generator",
      //   title: "invoice Re-Generator",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/subcategory/inVoiceRegenerator",
      // },
      // {
      //   id: "invoices",
      //   title: "invoices",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/subcategory/inVoices",
      // },
      // {
      //   id: "Payment Status",
      //   title: "Payment Status",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/subcategory/PaymentStatus",
      // },
      // {
      //   id: "Payment completed",
      //   title: "Payment completed",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/subcategory/paymentcompleted",
      // },
      // {
      //   type: "groupHeader",
      //   groupTitle: "Budget",
      //   title: "Budget",
      // },
      // {
      //   id: "budgetlist",
      //   title: "Budget List",
      //   type: "item",
      //   icon: <FaList size={15} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/cart/budgetlist",
      // },
      // {
      //   id: "Budget Assignment",
      //   title: "Budget Assignment",
      //   type: "item",
      //   icon: <FaList size={15} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/cart/BudgetAssignment",
      // },
    ],
  },

  {
    type: "groupHeader",
    groupTitle: "Warranty Management",
    title: "Warranty Management",
  },
  {
    id: "Warranty create",
    title: "Create Warranty",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "CreateWarrenty",
        title: "Create Warranty",
        type: "item",
        icon: <FaList size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/createWarrenty",
      },
      {
        id: "Search Warranty",
        title: "Search Warranty",
        type: "item",
        icon: <FaList size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/SearchWarrenty",
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "Warranty Claims",
    title: "Warranty Claims",
  },
  {
    id: "Warranty Claims",
    title: "Warranty Claims",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "OEM Warranty",
        title: "OEM Warranty",
        type: "item",
        icon: <FaList size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/OEMWarranty",
      },
      {
        id: "Supplier Warranty",
        title: "Suppier Warranty",
        type: "item",
        icon: <FaList size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/SupplierWarranty",
      },
    ],
  },

  {
    type: "groupHeader",
    groupTitle: "Stock Management",
    title: "Stock Management",
  },

  {
    id: "Stock Management",
    title: "Stock Management",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "Stock Report",
        title: "Stock Report",
        type: "item",
        icon: <FaProductHunt size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/report/stockReport",
      },

      {
        id: "Stock Transfer",
        title: "Stock Transfer",
        type: "item",
        icon: <FaProductHunt size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/report/StockTransfer",
      },
    ],
  },

  {
    type: "groupHeader",
    groupTitle: "Ticketing",
    title: "Ticketing",
  },
  {
    id: "Ticketing",
    title: "Ticketing",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "Service Request",
        title: "Service Request",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/ticketing/ServiceRequest",
      },
      {
        id: "Draft Service",
        title: "Draft Service",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/ticketing/DraftService",
      },
      {
        id: "Pending Service",
        title: "Pending Service",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/ticketing/PendingService",
      },
      {
        id: "Completed Service",
        title: "Completed Service",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/ticketing/CompletedService",
      },
      {
        id: "Transfer Service",
        title: "Transfer Service",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/ticketing/TransferService",
      },
      {
        id: "Cancelled Service",
        title: "Cancelled Service",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/ticketing/CancelledService",
      },
      {
        id: "Rejected Service",
        title: "Rejected Service",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/ticketing/RejectedService",
      },
    ],
  },

  {
    type: "groupHeader",
    groupTitle: "Reports Management",
    title: "Reports Management",
  },
  {
    id: "Reports Management",
    title: "Reports Management",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "AdminReport",
        title: "Admin Report",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/cart/DateWiseReport",
      },
      {
        id: "Customer Report",
        title: "Customer Report",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/report/CustomerReports",
      },
      {
        id: "Staff Report",
        title: "Staff Report",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/report/StaffReport",
      },
      // {
      //   id: "Client Wise",
      //   title: "Client Wise",
      //   type: "item",
      //   icon: <FaCircleNotch size={15} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/cart/Clientwisereport",
      // },
      {
        id: "Transaction Report",
        title: "Transaction Report",
        type: "item",
        icon: <FaCodeBranch size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/cart/BranchwiseReport",
      },
      {
        id: "Product Report",
        title: "Product Report",
        type: "item",
        icon: <FaProductHunt size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/report/ProductReports",
      },
      {
        id: "Earning Report",
        title: "Earning Report",
        type: "item",
        icon: <FaProductHunt size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/report/EarningReport",
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "Promotion Management",
    title: "Promotion Management",
  },
  {
    id: "Promotion Management",
    title: "Promotion Management",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "Promotion",
        title: "Promotion",
        type: "item",
        icon: <FaCode size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/promotion/Promotion",
      },
      {
        id: "Discount&Coupon",
        title: "Discount&Coupon",
        type: "item",
        icon: <FaCode size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/promotion/DiscountCoupon",
      },
    ],
  },

  {
    type: "groupHeader",
    groupTitle: "Media Status Management",
    title: "Media Status Management",
  },
  {
    id: "Media Status Management",
    title: "Media Status Management",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "LivestreamStatus",
        title: "LivestreamStatus",
        type: "item",
        icon: <FaCode size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/media/Livestreamstatus",
      },
      {
        id: "ChatStatus",
        title: "ChatStatus",
        type: "item",
        icon: <FaCode size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/media/ChatStatus",
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "Product Wiki",
    title: "Product Wiki",
  },
  {
    id: "Product",
    title: "Product",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "Product Wiki",
        title: "Create WIKI",
        type: "item",
        icon: <FaCode size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/CreateWiki",
      },
      {
        id: "WIKI List",
        title: "WIKI List",
        type: "item",
        icon: <FaCode size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/WikiList",
      },
    ],
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Logs",
  //   title: "Logs",
  // },
  // {
  //   id: "Logs",
  //   title: "Logs",
  //   type: "item",
  //   icon: <FaList size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/report/LogsReport",
  // },
  // {
  //   id: "refund",
  //   title: "Refund Requests",
  //   type: "collapse",
  //   icon: <FaRegFileAlt size={15} />,
  //   children: [
  //     {
  //       id: "pending",
  //       title: "Pending",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/refundrequest/pendingRequest",
  //     },
  //     {
  //       id: "approv",
  //       title: "Approved",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/refundrequest/approvedRequest",
  //     },

  //     {
  //       id: "comp",
  //       title: "Completed",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/refundrequest/completedRequest",
  //     },
  //     {
  //       id: "reject",
  //       title: "Rejected",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/refundrequest/rejectedRequest",
  //     },
  //   ],
  // },

  // {
  //   id: "batch",
  //   title: "Batch",
  //   type: "collapse",
  //   icon: <FaStar size={15} />,
  //   children: [
  //     {
  //       id: "batchList",
  //       title: "Batch List",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/batch/batchList",
  //     },
  //   ],
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "CUSTOMER MANAGEMENT",
  // },
  // {
  //   id: "customer",
  //   title: "Customers  ",
  //   type: "collapse",
  //   icon: <FaWallet size={15} />,
  //   children: [
  //     {
  //       id: "customergroup",
  //       title: "Customer Group",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/customer/customergroup",
  //     },
  //     {
  //       id: "list",
  //       title: "Customer List",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/customer/customerList",
  //     },
  //   ],
  // },

  // {
  //   id: "holiday",
  //   title: "Holiday Management",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/cart/suggestedProducts",
  // },
  // {
  //   id: "weekdays",
  //   title: "Weekdays",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/cart/suggestedProducts",
  // },
  // {
  //   id: "Export&Import",
  //   title: "BULK Export And Import",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/cart/suggestedProducts",
  // },

  // {
  //   id: "wallet",
  //   title: "Wallet",
  //   type: "collapse",
  //   icon: <FaCircle size={8} />,
  //   children: [
  //     {
  //       id: "credit",
  //       title: "Credit/Debit",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/wallet/walletType",
  //     },
  //   ],
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "DRIVER MANAGEMENT",
  // },
  // {
  //   id: "driver",
  //   title: "Driver",
  //   type: "collapse",
  //   icon: <FaUser size={15} />,
  //   children: [
  //     {
  //       id: "addriver",
  //       title: "Add Driver",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/driver/addDriver",
  //     },
  //     {
  //       id: "driverList",
  //       title: "Driver List",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/driver/driverList",
  //     },
  //   ],
  // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "SUBSCRIPTIONS MANAGEMENT",
  // },
  // {
  //   id: "subscriptions",
  //   title: "Subscriptions",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/subscriber/subscriberList",
  // },
  // {
  //   id: "vendor",
  //   title: "Vendors",
  //   type: "collapse",
  //   icon: <FaUsers size={15} />,
  //   children: [
  //     {
  //       id: "vendor",
  //       title: "Add Vendors  ",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/vendor/addVendor",
  //     },
  //     {
  //       id: "vendor_list",
  //       title: "Vendors List",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/vendor/vendorList",
  //     },
  //     {
  //       id: "withdraw",
  //       title: "Withdraws",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/vendor/withDraws",
  //     },
  //   ],
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Hub MANAGEMENT",
  // },
  // {
  //   id: "hub",
  //   title: "Hub",
  //   type: "collapse",
  //   icon: <FaShoppingCart size={15} />,
  //   children: [
  //     // {
  //     //   id: "addhub",
  //     //   title: "AddHub",
  //     //   type: "item",
  //     //   icon: <FaCircle size={8} />,
  //     //   permissions: ["admin", "editor"],
  //     //   navLink: "/app/freshlist/hubs/addhub",
  //     // },
  //     // {
  //     //   id: "hubList",
  //     //   title: "HubList",
  //     //   type: "item",
  //     //   icon: <FaCircle size={8} />,
  //     //   permissions: ["admin", "editor"],
  //     //   navLink: "/app/freshlist/hubs/hubList",
  //     // },
  //   ],
  // },
  // {
  //   id: "language",
  //   title: "Language",
  //   type: "item",
  //   icon: <FaCircle size={8} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/language/languageList",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Web Banner Management",
  // },
  // {
  //   id: "homepage",
  //   title: "Home Page",
  //   type: "item",
  //   icon: <BsImage size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/banner/reportsdatewise",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Mobile App Management",
  // },
  // {
  //   id: "bannerSection",
  //   title: "Banner with section Colours",
  //   type: "item",
  //   icon: <GiWantedReward size={18} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/mobile/bannerSection",
  // },
  // {
  //   id: "notification",
  //   title: "Notification",
  //   type: "collapse",
  //   icon: <GiWantedReward size={18} />,
  //   children: [
  //     {
  //       id: "all",
  //       title: "All",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/mobile/allNotify",
  //     },
  //     {
  //       id: "customerGroupWise",
  //       title: "Customer Group Wise",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/mobile/customerGroupWise",
  //     },
  //   ],
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: " Banner Management",
  // },
  // {
  //   id: "Banner",
  //   title: "Banner",
  //   type: "item",
  //   icon: <BsImage size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/banner/reportsdatewise",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "PROMOTION MANAGEMENT",
  // },

  // {
  //   id: "special",
  //   title: "Special",
  //   type: "item",
  //   icon: <MdOutlineFolderSpecial size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/special/SpecialList",
  // },
  // {
  //   id: "discount",
  //   title: "Discount",
  //   type: "item",
  //   icon: <CiDiscount1 size={18} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/discount/DiscountList",
  // },
  // {
  //   id: "reward_point",
  //   title: "Reward Point",
  //   type: "item",
  //   icon: <GiWantedReward size={18} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/points/points",
  // },

  // {
  //   id: "offer&deal",
  //   title: "Offers & Deals",
  //   type: "collapse",
  //   icon: <FaUsers size={15} />,
  //   children: [
  //     {
  //       id: "couponcode",
  //       title: "Coupon Code",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/coupon/couponList",
  //     },
  //     {
  //       id: "flashSale",
  //       title: "Referal Code",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/flashSale/flashSale",
  //     },
  //     {
  //       id: "dealOfDay",
  //       title: "Hub Delivery",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/dealOfDay/DealOfDay",
  //     },
  //     {
  //       id: "featuredeal",
  //       title: " Pin Code",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/featuredeal/featuredeal",
  //     },
  //     {
  //       id: "notification",
  //       title: "Delivery Cities",
  //       type: "item",
  //       icon: <GiWantedReward size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/notif/notification",
  //     },
  //   ],
  // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "ZONE MANAGEMENT",
  // },
  // {
  //   id: "deliveryCharges",
  //   title: "DeliveryCharges",
  //   type: "item",
  //   icon: <FaStar size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/zone/AddDeliveryCharges",
  // },

  // {
  //   id: "addzone",
  //   title: "Add Zone",
  //   type: "item",
  //   icon: <TbTruckDelivery size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/zone/addzone",
  // },
  // {
  //   id: "zoneslist",
  //   title: "ZonesList",
  //   type: "item",
  //   icon: <TbTruckDelivery size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/zone/zoneslist",
  // },

  // {
  //   id: "taxreport",
  //   title: "Tax Report  ",
  //   type: "item",
  //   icon: <FiBarChart2 size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/report/taxReport",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Report MANAGEMENT",
  // },

  // {
  //   id: "sales",
  //   title: "Sales",
  //   type: "collapse",
  //   icon: <FaWallet size={15} />,
  //   children: [
  //     {
  //       id: "totalSales",
  //       title: "Total Sale",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/sales/totalSales",
  //     },
  //     // {
  //     //   id: "hubSales",
  //     //   title: "Hub Sale",
  //     //   type: "item",
  //     //   icon: <FaCircle size={8} />,
  //     //   permissions: ["admin", "editor"],
  //     //   navLink: "/app/freshlist/sales/hubSales",
  //     // },
  //   ],
  // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Pages & MEDIA MANAGEMENT",
  // },
  // {
  //   id: "gallery",
  //   title: "Gallery",
  //   type: "item",
  //   icon: <TbTruckDelivery size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/gallery/gallery",
  // },
  // {
  //   id: "term & condition",
  //   title: "Term & Condition",
  //   type: "item",
  //   icon: <FaFileSignature size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/termsAndCondition/TAndCList",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Option MANAGEMENT",
  // },
  // {
  //   id: "attributelist",
  //   title: "AttributeList",
  //   type: "item",
  //   icon: <FaCircle size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/options/AttributeList",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "USER MANAGEMENT",
  // },
  // {
  //   id: "employee",
  //   title: "Employee",
  //   type: "collapse",
  //   icon: <FaUser size={15} />,
  //   children: [
  // {
  //   id: "setup",
  //   title: "Manage Role",
  //   type: "item",
  //   icon: <FaCircle size={8} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/user/manageRole",
  //   // navLink: "/app/freshlist/user/customsetuprole",
  // },
  // {
  //   id: "manageUsers",
  //   title: "Manage Users",
  //   type: "item",
  //   icon: <FaCircle size={8} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/user/userlist",
  //   // navLink: "/app/freshlist/user/employeeslist",
  // },
  //   ],
  // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Freebies MANAGEMENT",
  // },
  // {
  //   id: "manageFreebies",
  //   title: "Manage Freebies",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/freebies/freebies",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Cart MANAGEMENT",
  // },
  // {
  //   id: "suggestedProducts",
  //   title: "Suggested Products",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/cart/suggestedProducts",
  // },
  {
    type: "groupHeader",
    groupTitle: "SUPPORT MANAGEMENT",
  },

  {
    id: "Supportcreate",
    title: "Support Create",
    type: "item",
    icon: <FaCog size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/softNumen/warranty/CreateSupport",
  },
  {
    id: "Supportsearch",
    title: "Support search",
    type: "item",
    icon: <FaCog size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/softNumen/warranty/SupportSearch",
  },
  {
    id: "helpAndSupport",
    title: "Help And Support",
    type: "item",
    icon: <FaQuestionCircle size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/softNumen/support/HelpandSupports",
  },
  {
    id: "logout",
    title: "Logout",
    type: "item",
    icon: <Icon.ArrowRight size={15} />,
    permissions: ["admin", "editor"],
  },

  // {
  //   id: "subscription",
  //   title: "Subscriptions",
  //   type: "item",
  //   // icon: <Icon.Youtube size={20} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/marketing/subscription/subscriptionList",
  // },
  // {
  //   id: "invoiceSetting",
  //   title: "Invoice Setting ",
  //   type: "item",
  //   icon: < FaCircle size={12}/>,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/order/invoiceSetting",
  // },
  // {
  //   id: "invoiceDesign",
  //   title: "Invoice Design ",
  //   type: "item",
  //   icon: < FaCircle size={12}/>,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/order/invoiceDesign",
  // },
  // {
  //   id: "bank",
  //   title: "Bank",
  //   type: "collapse",
  //    icon: < FaHouseDamage size={20} />,
  //    children: [
  //     {
  //       id: "bank",
  //       title: "bank Details",
  //       type: "item",
  //       icon: < FaCircle size={12}/>,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/bank/bank",
  //     },
  //   ]
  // },
  //     {
  //       id: "pushnotification",
  //       title: "Push Notification",
  //       type: "item",
  //       icon: < FaCircle size={12}/>,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/marketing/pushnotification/addPushnotification",
  //     },

  //      {
  //        id: "variantList",
  //        title: "Variant",
  //        type: "item",
  //        icon: <Icon.Circle size={12} />,
  //        permissions: ["admin", "editor"],
  //        navLink: "/app/productManagement/variant/variantList",
  //      },
  //      {
  //        id: "unitsList",
  //        title: "Units",
  //        type: "item",
  //        icon: <Icon.Circle size={12} />,
  //        permissions: ["admin", "editor"],
  //        navLink: "/app/productManagement/units/unitsList",
  //     },
];
export default navigationConfig;
